TOOL_NAME = extrainst_
extrainst__INSTALL_PATH = /DEBIAN

extrainst__OBJC_FILES = main.mm
extrainst__CODESIGN_FLAGS="-SEntitlements.plist"

ARCHS := arm64 arm64e

include $(THEOS)/makefiles/common.mk
include $(THEOS)/makefiles/tool.mk
